# Generated by Django 3.0.8 on 2020-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolutions',
            field=models.TextField(default='{}'),
        ),
    ]
