# Generated by Django 3.0.8 on 2020-08-01 18:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_evolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
