# Generated by Django 3.0.8 on 2020-08-01 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_numberadsda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='numberadsda',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
    ]
