# Generated by Django 3.0.8 on 2020-08-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20200801_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonPost',
        ),
    ]
