# Generated by Django 3.0.8 on 2020-08-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_delete_pokemonpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='exp',
            field=models.IntegerField(default=1),
        ),
    ]
