# Generated by Django 3.0.8 on 2020-08-01 01:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20200723_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolve_chain',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='prev_exp',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=25), default='error', size=None),
        ),
    ]
