# Generated by Django 3.0.8 on 2020-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20200806_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='back_sprite',
            field=models.URLField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='main_pic',
            field=models.URLField(default='https://assets.pokemon.com/assets/cms2/img/pokedex/full/3.png'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png'),
        ),
    ]
